-- we don't know how to generate root <with-no-name> (class Root) :(
create table if not exists PUBLIC.CATEGORY
(
    ID   INTEGER auto_increment
        primary key,
    NAME CHARACTER VARYING(255) not null
);

create table if not exists INFORMATION_SCHEMA.CONSTANTS
(
    CONSTANT_CATALOG           CHARACTER VARYING,
    CONSTANT_SCHEMA            CHARACTER VARYING,
    CONSTANT_NAME              CHARACTER VARYING,
    VALUE_DEFINITION           CHARACTER VARYING,
    DATA_TYPE                  CHARACTER VARYING,
    CHARACTER_MAXIMUM_LENGTH   BIGINT,
    CHARACTER_OCTET_LENGTH     BIGINT,
    CHARACTER_SET_CATALOG      CHARACTER VARYING,
    CHARACTER_SET_SCHEMA       CHARACTER VARYING,
    CHARACTER_SET_NAME         CHARACTER VARYING,
    COLLATION_CATALOG          CHARACTER VARYING,
    COLLATION_SCHEMA           CHARACTER VARYING,
    COLLATION_NAME             CHARACTER VARYING,
    NUMERIC_PRECISION          INTEGER,
    NUMERIC_PRECISION_RADIX    INTEGER,
    NUMERIC_SCALE              INTEGER,
    DATETIME_PRECISION         INTEGER,
    INTERVAL_TYPE              CHARACTER VARYING,
    INTERVAL_PRECISION         INTEGER,
    MAXIMUM_CARDINALITY        INTEGER,
    DTD_IDENTIFIER             CHARACTER VARYING,
    DECLARED_DATA_TYPE         CHARACTER VARYING,
    DECLARED_NUMERIC_PRECISION INTEGER,
    DECLARED_NUMERIC_SCALE     INTEGER,
    GEOMETRY_TYPE              CHARACTER VARYING,
    GEOMETRY_SRID              INTEGER,
    REMARKS                    CHARACTER VARYING
);

create table if not exists INFORMATION_SCHEMA.ENUM_VALUES
(
    OBJECT_CATALOG  CHARACTER VARYING,
    OBJECT_SCHEMA   CHARACTER VARYING,
    OBJECT_NAME     CHARACTER VARYING,
    OBJECT_TYPE     CHARACTER VARYING,
    ENUM_IDENTIFIER CHARACTER VARYING,
    VALUE_NAME      CHARACTER VARYING,
    VALUE_ORDINAL   CHARACTER VARYING
);

create table if not exists INFORMATION_SCHEMA.INDEXES
(
    INDEX_CATALOG   CHARACTER VARYING,
    INDEX_SCHEMA    CHARACTER VARYING,
    INDEX_NAME      CHARACTER VARYING,
    TABLE_CATALOG   CHARACTER VARYING,
    TABLE_SCHEMA    CHARACTER VARYING,
    TABLE_NAME      CHARACTER VARYING,
    INDEX_TYPE_NAME CHARACTER VARYING,
    IS_GENERATED    BOOLEAN,
    REMARKS         CHARACTER VARYING,
    INDEX_CLASS     CHARACTER VARYING
);

create table if not exists INFORMATION_SCHEMA.INDEX_COLUMNS
(
    INDEX_CATALOG          CHARACTER VARYING,
    INDEX_SCHEMA           CHARACTER VARYING,
    INDEX_NAME             CHARACTER VARYING,
    TABLE_CATALOG          CHARACTER VARYING,
    TABLE_SCHEMA           CHARACTER VARYING,
    TABLE_NAME             CHARACTER VARYING,
    COLUMN_NAME            CHARACTER VARYING,
    ORDINAL_POSITION       INTEGER,
    ORDERING_SPECIFICATION CHARACTER VARYING,
    NULL_ORDERING          CHARACTER VARYING,
    IS_UNIQUE              BOOLEAN
);

create table if not exists PUBLIC.INFORMATION
(
    ID          INTEGER auto_increment
        primary key,
    TITLE       CHARACTER VARYING(255) not null,
    CONTENT     CHARACTER VARYING(255) not null,
    DATE        DATE                   not null,
    CATEGORY_ID INTEGER,
    LINK        CHARACTER VARYING(255)
);

create table if not exists INFORMATION_SCHEMA.INFORMATION_SCHEMA_CATALOG_NAME
(
    CATALOG_NAME CHARACTER VARYING
);

create table if not exists INFORMATION_SCHEMA.IN_DOUBT
(
    TRANSACTION_NAME  CHARACTER VARYING,
    TRANSACTION_STATE CHARACTER VARYING
);

create table if not exists INFORMATION_SCHEMA.LOCKS
(
    TABLE_SCHEMA CHARACTER VARYING,
    TABLE_NAME   CHARACTER VARYING,
    SESSION_ID   INTEGER,
    LOCK_TYPE    CHARACTER VARYING
);

create table if not exists INFORMATION_SCHEMA.QUERY_STATISTICS
(
    SQL_STATEMENT             CHARACTER VARYING,
    EXECUTION_COUNT           INTEGER,
    MIN_EXECUTION_TIME        DOUBLE PRECISION,
    MAX_EXECUTION_TIME        DOUBLE PRECISION,
    CUMULATIVE_EXECUTION_TIME DOUBLE PRECISION,
    AVERAGE_EXECUTION_TIME    DOUBLE PRECISION,
    STD_DEV_EXECUTION_TIME    DOUBLE PRECISION,
    MIN_ROW_COUNT             BIGINT,
    MAX_ROW_COUNT             BIGINT,
    CUMULATIVE_ROW_COUNT      BIGINT,
    AVERAGE_ROW_COUNT         DOUBLE PRECISION,
    STD_DEV_ROW_COUNT         DOUBLE PRECISION
);

create table if not exists INFORMATION_SCHEMA.RIGHTS
(
    GRANTEE      CHARACTER VARYING,
    GRANTEETYPE  CHARACTER VARYING,
    GRANTEDROLE  CHARACTER VARYING,
    RIGHTS       CHARACTER VARYING,
    TABLE_SCHEMA CHARACTER VARYING,
    TABLE_NAME   CHARACTER VARYING
);

create table if not exists INFORMATION_SCHEMA.ROLES
(
    ROLE_NAME CHARACTER VARYING,
    REMARKS   CHARACTER VARYING
);

create table if not exists INFORMATION_SCHEMA.SESSIONS
(
    SESSION_ID                INTEGER,
    USER_NAME                 CHARACTER VARYING,
    SERVER                    CHARACTER VARYING,
    CLIENT_ADDR               CHARACTER VARYING,
    CLIENT_INFO               CHARACTER VARYING,
    SESSION_START             TIMESTAMP(9) WITH TIME ZONE,
    ISOLATION_LEVEL           CHARACTER VARYING,
    EXECUTING_STATEMENT       CHARACTER VARYING,
    EXECUTING_STATEMENT_START TIMESTAMP(9) WITH TIME ZONE,
    CONTAINS_UNCOMMITTED      BOOLEAN,
    SESSION_STATE             CHARACTER VARYING,
    BLOCKER_ID                INTEGER,
    SLEEP_SINCE               TIMESTAMP(9) WITH TIME ZONE
);

create table if not exists INFORMATION_SCHEMA.SESSION_STATE
(
    STATE_KEY     CHARACTER VARYING,
    STATE_COMMAND CHARACTER VARYING
);

create table if not exists INFORMATION_SCHEMA.SETTINGS
(
    SETTING_NAME  CHARACTER VARYING,
    SETTING_VALUE CHARACTER VARYING
);

create table if not exists INFORMATION_SCHEMA.SYNONYMS
(
    SYNONYM_CATALOG    CHARACTER VARYING,
    SYNONYM_SCHEMA     CHARACTER VARYING,
    SYNONYM_NAME       CHARACTER VARYING,
    SYNONYM_FOR        CHARACTER VARYING,
    SYNONYM_FOR_SCHEMA CHARACTER VARYING,
    TYPE_NAME          CHARACTER VARYING,
    STATUS             CHARACTER VARYING,
    REMARKS            CHARACTER VARYING
);

create table if not exists INFORMATION_SCHEMA.USERS
(
    USER_NAME CHARACTER VARYING,
    IS_ADMIN  BOOLEAN,
    REMARKS   CHARACTER VARYING
);

